from aiogram.types import Message
from bitcrawler.utils.utils import bq


async def still_alive(message: Message):
    await message.reply(
        bq(
            "This was a triumph\n"
            "I'm making a note here; \"Huge success\"\n"
            "It's hard to overstate\n"
            "My satisfaction\n"
            "Aperture Science:\n"
            "We do what we must\n"
            "Because we can\n"
            "For the good of all of us\n"
            "Except the ones who are dead\n"
            "But there's no sense crying\n"
            "Over every mistake\n"
            "You just keep on trying\n"
            "Till you run out of cake\n"
            "And the science gets done\n"
            "And you make a neat gun\n"
            "For the people who are\n"
            "Still alive\n"
            "I'm not even angry\n"
            "I'm being so sincere right now\n"
            "Even though you broke my heart,\n"
            "And killed me\n"
            "And tore me to pieces\n"
            "And threw every piece into a fire\n"
            "As they burned it hurt because\n"
            "I was so happy for you\n"
            "Now, these points of data\n"
            "Make a beautiful line\n"
            "And we're out of beta\n"
            "We're releasing on time\n"
            "So I'm GLaD I got burned\n"
            "Think of all the things we learned-\n"
            "For the people who are\n"
            "Still alive\n"
            "Go ahead and leave me\n"
            "I think I'd prefer to stay inside\n"
            "Maybe you'll find someone else\n"
            "To help you?\n"
            "Maybe Black Mesa?\n"
            "That was a joke *Haha - Fat Chance*\n"
            "Anyway this cake is great\n"
            "It's so delicious and moist\n"
            "Look at me: still talking\n"
            "When there's science to do\n"
            "When I look out there,\n"
            "It makes me GLaD I'm not you\n"
            "I've experiments to run\n"
            "There is research to be done\n"
            "On the people who are\n"
            "Still alive\n"
            "And believe me I am\n"
            "Still alive\n"
            "I'm doing science and I'm\n"
            "Still alive\n"
            "I feel fantastic and I'm\n"
            "Still alive\n"
            "While you're dying I'll be\n"
            "Still alive\n"
            "And when you're dead I will be\n"
            "Still alive\n"
            "Still alive\n"
        ),
        parse_mode="HTML"
    )
